/**
 * 场景样例应用清单（本地 / 远程 MySQL 对齐用）
 * 部署不会拷贝数据库，启动时用 ensureSceneProducts 按此 upsert 名称与落地页。
 */
export const SCENE_CATEGORY = {
  campus: "校园",
  social: "社交",
  charity: "公益",
  fitness: "健身",
  outdoor: "户外",
};

export const SCENE_COLOR = {
  campus: "#5C6BC0",
  social: "#EC407A",
  charity: "#66BB6A",
  fitness: "#FF7043",
  outdoor: "#26A69A",
};

export const SEED_APPS = [
  {
    sceneId: "campus",
    apps: [
      {
        name: "书市雷达",
        slug: "shushi-radar",
        platform: "pc",
        tagline: "校园二手书就近撮合，下课就能当面交易",
        topic: "校园二手书买卖",
        tool: "华为码道",
        views: 1280,
        shares: 36,
        votes: 42,
      },
      {
        name: "篮搭一下",
        slug: "landa",
        platform: "h5",
        tagline: "约球、凑人、订场地，一键找到同校球友",
        topic: "校园篮球搭子",
        tool: "WorkBuddy",
        views: 960,
        shares: 22,
        votes: 31,
      },
      {
        name: "招领雷达",
        slug: "zhaoling-radar",
        platform: "h5",
        tagline: "校园失物招领信息聚合，附近捡到的先看到",
        topic: "失物招领雷达",
        tool: "千问 Work",
        views: 740,
        shares: 18,
        votes: 25,
      },
      {
        name: "食堂拼团王",
        slug: "shitang-pintuan",
        platform: "h5",
        tagline: "校园食堂拼团下单，同楼同宿舍更快成团",
        topic: "校园周边餐厅团购",
        tool: "WorkBuddy",
        views: 860,
        shares: 19,
        votes: 28,
      },
    ],
  },
  {
    sceneId: "social",
    apps: [
      {
        name: "饭搭子计划",
        slug: "fandazi",
        platform: "h5",
        tagline: "周末同城拼饭，按口味与距离智能匹配",
        topic: "周末饭搭子组局",
        tool: "WorkBuddy",
        views: 1520,
        shares: 48,
        votes: 55,
      },
      {
        name: "本杀开黑台",
        slug: "bensha",
        platform: "h5",
        tagline: "剧本杀 / 狼人杀一键组局，缺人就来补",
        topic: "剧本杀狼人杀组局",
        tool: "Trae Work",
        views: 880,
        shares: 27,
        votes: 29,
      },
      {
        name: "遛宠圈",
        slug: "liuchong",
        platform: "h5",
        tagline: "同城遛宠搭子与路线分享，遛狗也能社交",
        topic: "宠物遛弯社交圈",
        tool: "华为码道",
        views: 690,
        shares: 15,
        votes: 21,
      },
    ],
  },
  {
    sceneId: "charity",
    apps: [
      {
        name: "旧物捐赠地图",
        slug: "jiuwu-juanzeng",
        platform: "pc",
        tagline: "附近捐赠点与上门回收一站查询",
        topic: "旧物捐赠地图",
        tool: "千问 Work",
        views: 1100,
        shares: 40,
        votes: 38,
      },
      {
        name: "志愿时长本",
        slug: "zhiyuan-shichang",
        platform: "h5",
        tagline: "志愿活动签到与时长自动记账",
        topic: "志愿时长记账本",
        tool: "WorkBuddy",
        views: 620,
        shares: 12,
        votes: 19,
      },
      {
        name: "流浪助养台",
        slug: "liulang-zhuyang",
        platform: "pc",
        tagline: "流浪动物救助信息与临时寄养对接",
        topic: "流浪动物救助台",
        tool: "华为码道",
        views: 830,
        shares: 33,
        votes: 28,
      },
    ],
  },
  {
    sceneId: "fitness",
    apps: [
      {
        name: "私教拼搭",
        slug: "sijiao-pinda",
        platform: "h5",
        tagline: "健身房私教课拼人更划算",
        topic: "健身房私教搭子",
        tool: "Trae Work",
        views: 990,
        shares: 24,
        votes: 34,
      },
      {
        name: "热量一眼过",
        slug: "reliang",
        platform: "h5",
        tagline: "食堂菜品拍照估热量，轻食选择更简单",
        topic: "食堂热量识别",
        tool: "华为码道",
        views: 1340,
        shares: 41,
        votes: 47,
      },
      {
        name: "跑线推荐",
        slug: "paoxian",
        platform: "pc",
        tagline: "按配速与路况推荐城市跑步路线",
        topic: "跑步路线推荐",
        tool: "WorkBuddy",
        views: 870,
        shares: 20,
        votes: 30,
      },
    ],
  },
  {
    sceneId: "outdoor",
    apps: [
      {
        name: "徒步组队社",
        slug: "tubo",
        platform: "pc",
        tagline: "周末徒步路线与队友一键成团",
        topic: "周末徒步组队",
        tool: "WorkBuddy",
        views: 1210,
        shares: 39,
        votes: 44,
      },
      {
        name: "露营装备单",
        slug: "luying-zhuangbei",
        platform: "pc",
        tagline: "按人数与天气生成露营装备清单",
        topic: "露营装备清单",
        tool: "千问 Work",
        views: 780,
        shares: 17,
        votes: 23,
      },
      {
        name: "骑行城市线",
        slug: "qixing",
        platform: "pc",
        tagline: "城市骑行路线与补给点推荐",
        topic: "城市骑行路线",
        tool: "华为码道",
        views: 1050,
        shares: 29,
        votes: 36,
      },
    ],
  },
];

export function appDeployUrl(slug) {
  return `/apps/${slug}/`;
}
